2021/01/27 11:25:10 : Error Connecting:HTTPConnectionPool(host='192.168.31.103', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b2cc510>: Failed to establish a new connection: [Errno 61] Connection refused')) : False
